name: intothemoss-cms

services:
  - name: web
    github:
      repo: IntoTheMoss/podcast_cms
      branch: main
    build_command: pip install -r requirements.txt && python manage.py collectstatic --noinput
    run_command: gunicorn intothemoss_cms.wsgi:application --workers 3 --timeout 120
    http_port: 8000
    envs:
      - key: DJANGO_SETTINGS_MODULE
        value: intothemoss_cms.settings
      - key: DJANGO_SECRET_KEY
        value: ${DJANGO_SECRET_KEY}
      - key: DJANGO_ALLOWED_HOSTS
        value: ".ondigitalocean.app,dev.intothemoss.com,www.intothemoss.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.ondigitalocean.app,https://dev.intothemoss.com,https://www.intothemoss.com"
      - key: DEBUG
        value: "False"
      - key: DEVELOPMENT_MODE
        value: "False"
      - key: DATABASE_URL
        value: ${podcast-db.DATABASE_URL}
      - key: WAGTAILADMIN_BASE_URL
        value: "https://intothemoss-wjgrx.ondigitalocean.app"
      - key: SPACES_KEY
        value: ${SPACES_KEY}
      - key: SPACES_SECRET
        value: ${SPACES_SECRET}
      - key: SPACES_BUCKET
        value: "intothemoss-media"
      - key: SPACES_REGION
        value: "fra1"
