version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    volumes:
      - ./media:/code/media:rw
      - ./static:/code/static:rw
      - ./logs:/code/logs:rw
    environment:
      - DATABASE_URL=postgres://intothemoss_user:${DB_PASSWORD}@db:5432/intothemoss_db
      - DJANGO_SETTINGS_MODULE=intothemoss_cms.settings.production
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DEBUG=False
    ports:
      - "8000:8000"
      
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      - POSTGRES_DB=intothemoss_db
      - POSTGRES_USER=intothemoss_user
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"   # Map container port 80 to host port 8080
      - "8443:443"  # Map container port 443 to host port 8443
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./static:/var/www/static
      - ./media:/var/www/media
      - /var/www/intothemoss/audio:/var/www/legacy/audio
      - /var/www/intothemoss/assets:/var/www/legacy/assets
      - /var/www/intothemoss/images:/var/www/legacy/images
    depends_on:
      - web
    restart: always

volumes:
  postgres_data: