version: '3'

services:
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./media:/code/media:rw
      - ./static:/code/static:rw
      - ./logs:/code/logs:rw
    environment:
      - DATABASE_URL=postgres://intothemoss_user:${DB_PASSWORD}@db:5432/intothemoss_db
      - DJANGO_SETTINGS_MODULE=intothemoss_cms.settings.production
    depends_on:
      - db
      
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=intothemoss_db
      - POSTGRES_USER=intothemoss_user
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/conf:/code/nginx/conf
      - ./nginx/ssl:/code/nginx/ssl
    depends_on:
      - web

volumes:
  postgres_data: