# Generated by Django 5.1.7 on 2025-03-16 10:37

import django.core.validators
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PodcastEpisodePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('episode_number', models.IntegerField(help_text='Episode number (must be unique)', validators=[django.core.validators.MinValueValidator(1)])),
                ('season_number', models.IntegerField(default=1, help_text='Season number', validators=[django.core.validators.MinValueValidator(1)])),
                ('publication_date', models.DateTimeField(help_text='When the episode was or should be published')),
                ('description', wagtail.fields.RichTextField(help_text='Brief description of the episode (appears in RSS feed)')),
                ('transcript', wagtail.fields.RichTextField(blank=True, help_text='Full transcript of the episode')),
                ('audio_file', models.FileField(help_text='MP3 audio file', upload_to='episodes/')),
                ('duration_in_seconds', models.PositiveIntegerField(blank=True, help_text='Duration in seconds (will be calculated automatically if blank)', null=True)),
                ('explicit_content', models.BooleanField(default=False, help_text='Mark if episode contains explicit content')),
                ('guid', models.CharField(blank=True, help_text='Unique identifier (will be generated automatically if blank)', max_length=64)),
                ('cover_image', models.ForeignKey(help_text='Episode cover image (1400x1400px recommended)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PodcastLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_links', to='podcast.podcastindexpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
