# Generated by Django 5.1.7 on 2025-09-14 15:38

import podcast.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcast", "0002_podcastepisodepage_season_episode_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcastepisodepage",
            name="audio_file",
            field=models.FileField(
                help_text="MP3 audio file",
                upload_to="episodes/",
                validators=[podcast.models.validate_mp3_file],
            ),
        ),
    ]
