# Generated by Django 5.1.7 on 2025-09-20 08:53

import django.db.models.deletion
from django.db import migrations, models
from datetime import date


class Migration(migrations.Migration):
    dependencies = [
        ("podcast", "0003_alter_podcastepisodepage_audio_file"),
        ("wagtailcore", "0095_groupsitepermission"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="PodcastSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Your Podcast",
                        help_text="The name of your podcast",
                        max_length=255,
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        default="Your Podcast subtitle",
                        help_text="Short description for podcast directories",
                        max_length=255,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        default="Your podcast summary",
                        help_text="Summary description for iTunes",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Your Podcast description.",
                        help_text="Full description for RSS feed",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        default="Your Name",
                        help_text="Author/creator name for the podcast",
                        max_length=255,
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(
                        default="Your Name",
                        help_text="Owner name for iTunes (can be multiple people)",
                        max_length=255,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="your@email.com",
                        help_text="Contact email for the podcast",
                        max_length=254,
                    ),
                ),
                (
                    "copyright_notice",
                    models.CharField(
                        default=f"© Your Podcast {date.today().year}",
                        help_text="Copyright notice for the podcast",
                        max_length=255,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en-uk",
                        help_text="Language code for the podcast (e.g. en-uk, en-us)",
                        max_length=10,
                    ),
                ),
                (
                    "cover_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Main podcast cover image (1400x1400px recommended)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Podcast Settings",
            },
        ),
    ]
