# Generated by Django 4.2.9 on 2025-11-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcast", "0004_podcastsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcastsettings",
            name="copyright_notice",
            field=models.CharField(
                default="© 2025 Your Podcast Name. All rights reserved.",
                help_text="Copyright notice for the podcast",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="podcastsettings",
            name="description",
            field=models.TextField(
                default="A full description of your podcast. Include what makes your podcast unique, who it's for, and what listeners can expect.",
                help_text="Full description for RSS feed",
            ),
        ),
        migrations.AlterField(
            model_name="podcastsettings",
            name="subtitle",
            field=models.CharField(
                default="A brief tagline for your podcast",
                help_text="Short description for podcast directories",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="podcastsettings",
            name="summary",
            field=models.TextField(
                default="A short summary of what your podcast is about",
                help_text="Summary description for iTunes",
            ),
        ),
        migrations.AlterField(
            model_name="podcastsettings",
            name="title",
            field=models.CharField(
                default="Your Podcast Name",
                help_text="The name of your podcast",
                max_length=255,
            ),
        ),
    ]
